### ISSUE TITLE
尝试直接通过 gorush 命令直接发送 ios 消息，失败，异常信息：

### ISSUE THREAD

**Issue by zhanghuid** [easychen/pushdeer#103]
**使用的是自架服务端，ios 商店下载的自架版**

**命令行推送异常截图**
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/12711819/162905241-42f9c891-8ecf-44ad-b660-7903f8184801.png">

**手机或电脑的的详细信息**
 - Device: [e.g. iPhone12]
 - OS: [e.g. iOS15.4.1]

 - 注册设备页面截图
![middle_img_v2_8ce76c61-3f27-4daa-ae62-9043e854b9eg](https://user-images.githubusercontent.com/12711819/162905627-2e7aae83-a840-460a-9903-3dba0f700aff.png)

**Comment by easychen** [comment]
图片中的提示信息是，deviceToken错误。这里的信息是apple直接返回的，说明在苹果那里这个deviceToken是不存在的。

**Comment by zhanghuid** [comment]
意识是说，在 由 pushdeer-自架版，上报的device_id
<img width="891" alt="image" src="https://user-images.githubusercontent.com/12711819/162963133-3cd5c449-f0ed-43f5-a2ad-d7c41c98e6ae.png">
是错误的？

导致，在通过 gorush 发送时，传入的 deviceToken 不对？

**Comment by easychen** [comment]
> 意思是说，在 由 pushdeer-自架版，上报的device_id <img alt="image" width="891" src="https://user-images.githubusercontent.com/12711819/162963133-3cd5c449-f0ed-43f5-a2ad-d7c41c98e6ae.png"> 是错误的？
> 
> 导致，在通过 gorush 发送时，传入的 deviceToken 不对？

deviceToken 可以通过 api 获取 https://github.com/easychen/pushdeer#%E8%AE%BE%E5%A4%87%E5%88%97%E8%A1%A8 ，你通过数据库查看也可以。

但 deviceToken 在应用重装以后会变。 另外也可能是证书（有两个，一个app一个clip）和deviceToken不匹配。

**Comment by zhanghuid** [comment]
**deviceToken** 我全试了一遍，都不得行

**证书：c.p12**，不是直接用 ios 目录下的么，也是不得行，命令如下：
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/12711819/163082157-5cc6f9e7-6adf-40d1-bda5-e4e242f6eb93.png">

**Comment by easychen** [comment]
> **deviceToken** 我全试了一遍，都不得行
> 
> **证书：c.p12**，不是直接用 ios 目录下的么，也是不得行，命令如下： <img alt="image" width="1082" src="https://user-images.githubusercontent.com/12711819/163082157-5cc6f9e7-6adf-40d1-bda5-e4e242f6eb93.png">

你这证书明明用的是 cc.p12 啊 🤣

**Comment by zhanghuid** [comment]
不好意思，刚刚穷举了所有的情况，下面是 c.p12的
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/12711819/163084542-56ae2b40-c8ca-4131-a154-f0660a175d4c.png">

**Comment by easychen** [comment]
> 不好意思，刚刚穷举了所有的情况，下面是 c.p12的 <img alt="image" width="1085" src="https://user-images.githubusercontent.com/12711819/163084542-56ae2b40-c8ca-4131-a154-f0660a175d4c.png">


![image](https://user-images.githubusercontent.com/1294760/163085452-59a2b179-9ef1-4e82-8a3e-6586743c98c2.png)

你用的topic 是pushdeer官方版的，要换成自架版 https://github.com/easychen/pushdeer/blob/a9ec7adfb09d6b4daa0022f728af70af45699c10/doc/%E8%B0%83%E8%AF%95%E6%96%87%E6%A1%A3.md#end-point-%E8%BF%9E%E9%80%9A%E6%80%A7%E6%B5%8B%E8%AF%95

**Comment by zhanghuid** [comment]
**topic: com.pushdeer.self.ios**
嗯，都试过了，都是一样的错：
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/12711819/163087170-62ab4e2a-404d-4dc6-afc2-fd4f0d80dad0.png">

**Comment by easychen** [comment]
> **topic: com.pushdeer.self.ios** 嗯，都试过了，都是一样的错： <img alt="image" width="1087" src="https://user-images.githubusercontent.com/12711819/163087170-62ab4e2a-404d-4dc6-afc2-fd4f0d80dad0.png">

我刚才自己架设了一个测试，自架版api接口推送是能用的。如果你确认所有参数和证书都正确，那么可能需要查看 gorush ( https://github.com/appleboy/gorush ) 文档，或者给他们提交issue 了。

**Comment by xkrfer** [comment]
我在黑苹果上拉gorush源码构建镜像，使用pm2 进行进程管理，启动clip+ios，很神奇的发现clip能发，ios不能发，查看日志发现发送到ios后，ios的gorush转发到clip了，导致clip找不到对应的deviceToken，后面在Linux / M1上构建才正常😂😂

**Comment by zhanghuid** [comment]
## 如下验证跟猜想，并非为了推广 `bark` ，只是做对比分析

## 进一步测试：
怀疑是 appstore 上的 自架版获取的 deviceToken 的问题？

### 验证：
1. 使用同款类型的推送工具[bark](https://day.app/2018/06/bark-server-document/)
2. 启动 gorush -c ios.yml
> ios.yml 的配置如下
<img width="874" alt="image" src="https://user-images.githubusercontent.com/12711819/163300023-15942765-e7c0-4913-aff7-9bdafd4711af.png">
>启动命令如下:
<img width="189" alt="image" src="https://user-images.githubusercontent.com/12711819/163300053-5134af44-2b8a-4728-a9ca-9812a0e35f13.png">

3. 发送情况：
<img width="1654" alt="image" src="https://user-images.githubusercontent.com/12711819/163299381-e2f6c22a-a069-46cf-a78a-aec4e630918a.png">
4. 是成功

### 结论：
如上验证过程好像没啥毛病，测试的最终结果也是OK的


## 猜想2
### 起因
在测试 `bark`时， 编排 ios.yml 的时候，看到一个配置项是 `false` 的，如下，也发送不了，改为 `true`，就能发送了
```
ios:
  production:false
```

### 猜想，会不会是，如论 `bark` 还是 `pushdeer` ，都是采用生产环境的的发送模式呢？
#### 验证
1. 更改 `ios.yml` 编排
```
ios:
  enabled: true
  key_path: "c.p12"
  key_base64: "" # load iOS key from base64 input
  key_type: "p12" # could be pem, p12 or p8 type
  password: "64wtMhU4mULj" # certificate password, default as empty string.
  production: true
  max_concurrent_pushes: 100 # just for push ios notification
  max_retry: 0 # resend fail notification, default value zero is disabled
  key_id: "66M7BD2GCV" # KeyID from developer account (Certificates, Identifiers & Profiles -> Keys)
  team_id: "HUJ6HAE4VU" # TeamID from developer account (View Account -> Membership)
```
2. 启动 & 测试
- 发送命令
```
 curl -X POST -H 'Content-Type: application/json' -d '{"notifications":[{"tokens":["A9C7BA4CD03C319579A071A3BFB**********CCD2633ACBD2C8E9C274D3A"],"platform":1,"message":"111","topic":"com.pushdeer.self.ios","sound":{"volume":2}}]}' http://127.0.0.1:8888/api/push

```
4. 效果截图
- 截图1
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/12711819/163300745-7968072b-3335-4853-9ee9-67e71922a104.png">

- 截图2
![image](https://user-images.githubusercontent.com/12711819/163300954-b4375e51-cb3c-4b67-aaac-f33b2bd6b637.png)


## 总结：
1. 为啥会有第一个猜想呢？是因为，我看了 [apns2](https://github.com/sideshow/apns2) 里发送的都是小写的 `deviceToken`
2. 不清楚 ios 的推送流程（包含 apns的推送模式，deviceToken 的获取方案，这里建议，pushdeer 也支持一下，能在设置里，显示 deviceToken，并支持复制）
