### ISSUE TITLE
PushDeer自架版，苹果通知中心没有提示，使用的单Docker文件

### ISSUE THREAD

**Issue by No-loveanymore** [easychen/pushdeer#125]
PushDeer自架版，苹果通知中心没有提示，使用的单Docker文件
App中收到了推送消息，但是软件退出后，推送通知不会显示在苹果的通知中心中

**Comment by zxb0303** [comment]
+1
ios版本为：15.5
型号：iPhone Xs Max
PushDeer自架版：1.7

**Comment by tuchief** [comment]
+1
ios版本为：15.6
PushDeer自架版：1.7

**Comment by Huangxt57** [comment]
+1
iOS: 15.5
PushDeer: 1.7

**Comment by easychen** [comment]
```yml
version: '2'
services:
  mariadb:
    image: 'mariadb:10.5.8-focal'
    volumes:
      - 'mariadb_data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=theVeryp@ssw0rd
      - MYSQL_DATABASE=pushdeer
    ports:
      - '3306:3306' 
  app:
    image: 'ccr.ccs.tencentyun.com/ftqq/pushdeercore'
    ports:
      - '80:9000'
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_DATABASE=pushdeer
      - DB_PASSWORD=theVeryp@ssw0rd
      - GO_PUSH_IOS_TOPIC=com.pushdeer.self.ios
      - GO_PUSH_IOS_CLIP_TOPIC=com.pushdeer.self.ios.Clip
      - APP_DEBUG=false
      - WEB_PHP_SOCKET=127.0.0.1:8000
      - MQTT_API_KEY={{$password}}
      - MQTT_ON=true
  mqtt:
   image: 'ccr.ccs.tencentyun.com/ftqq/pushdeeresp'
   ports:
     - '1883:1883'
   environment:
     - API_KEY={{$password}}
     - MQTT_PORT=1883
     - MQTT_USER=pushdeer
     - MQTT_PASSWORD={{$password}}
     - MQTT_BASE_TOPIC=default  
volumes:
  mariadb_data:
```

刚测试过没有发现问题。ipad OS 15.2
