### ISSUE TITLE
[Bug]修改数据库密码后docker-compose构建启动失败

### ISSUE THREAD

**Issue by zhuweitung** [easychen/pushdeer#74]
**描述你遇到的Bug**

修改`docker-compose.self-hosted.yml`文件中`MYSQL_ROOT_PASSWORD`和`DB_PASSWORD`的密码后（两个值一致），服务启动报错

**自架服务器端请填写以下信息**

按 [调试文档](https://github.com/easychen/pushdeer/blob/main/doc/调试文档.md) 进行调试的结果：

**API服务启动输出截图**

![image](https://user-images.githubusercontent.com/20264596/155085834-33ee1b3a-c1b5-4815-91db-4b85f0cc76b8.png)

**Comment by easychen** [comment]
MYSQL_ROOT_PASSWORD 是 mysql root账户的密码，如果使用它，DB_PASSWORD 不但要和 MYSQL_ROOT_PASSWORD 一直，DB_USERNAME 也必须为 root 。

**Comment by zhuweitung** [comment]
> 
数据库用户是root，我没改，下面是我的配置文件
```yml
version: '2'
services:
  mariadb:
    image: 'mariadb:10.5.8-focal'
    volumes:
      - 'mariadb_data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=KpLhwEN5zDwp@6ye
      - MYSQL_DATABASE=pushdeer
    ports:
      - '3306:3306' 
  redis: 
    image: 'bitnami/redis:6.0.16'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes 
  app:
    #image: 'webdevops/php-apache:8.0-alpine'
    build: './docker/web/'
    ports:
      - '8800:80'
    volumes:
      - './:/app'
    depends_on:
      - mariadb
      - redis
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_DATABASE=pushdeer
      - DB_PASSWORD=KpLhwEN5zDwp@6ye
      - GO_PUSH_IOS_TOPIC=com.pushdeer.self.ios
      - GO_PUSH_IOS_CLIP_TOPIC=com.pushdeer.self.ios.Clip
      - APP_DEBUG=false
      - MQTT_API_KEY=9LKo3
      - MQTT_ON=false
  # mqtt:
  #   image: 'ccr.ccs.tencentyun.com/ftqq/pushdeeresp'
  #   ports:
  #     - '1883:1883'
  #   environment:
  #     - API_KEY=9LKo3
  #     - MQTT_PORT=1883
  #     - MQTT_USER=easy
  #     - MQTT_PASSWORD=y0urp@ss
  #     - MQTT_BASE_TOPIC=default    
volumes:
  mariadb_data:
```
我只改了MYSQL_ROOT_PASSWORD和DB_PASSWORD
